# Generated by Django 4.0 on 2022-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=60)),
                ('teacher', models.CharField(max_length=62)),
                ('no_of_studs', models.IntegerField(default=0)),
            ],
        ),
    ]
